name: 'bookshop'
version: '1.0.0'
config-version: 2

profile: 'bookshop'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  bookshop:
    +materialized: table
    staging:
      +schema: STAGGING
      +materialized: table
    warehouse:
      +schema: WAREHOUSE
      +materialized: table
    marts:
      +schema: MARTS
      +materialized: table

vars:
  database: BOOKSHOP
  raw_schema: RAW
  staging_schema: STAGGING
  warehouse_schema: WAREHOUSE
  marts_schema: MARTS