bookshop:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN
      database: BOOKSHOP
      warehouse: COMPUTE_WH
      schema: STAGING
      threads: 1
      client_session_keep_alive: False
      query_tag: dbt
      retry_all: True
      retry_on_database_errors: True
      connect_retries: 3
      connect_timeout: 10
      schema_autocreate: True