{% macro grant_privileges() %}

{% set query %}
    USE ROLE ACCOUNTADMIN;
    GRANT ALL PRIVILEGES ON DATABASE {{ env_var('SNOWFLAKE_DATABASE') }} TO ROLE ACCOUNTADMIN;
    GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE {{ env_var('SNOWFLAKE_DATABASE') }} TO ROLE ACCOUNTADMIN;
    GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE {{ env_var('SNOWFLAKE_DATABASE') }} TO ROLE ACCOUNTADMIN;
    GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE {{ env_var('SNOWFLAKE_DATABASE') }} TO ROLE ACCOUNTADMIN;
    GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE {{ env_var('SNOWFLAKE_DATABASE') }} TO ROLE ACCOUNTADMIN;
{% endset %}

{% do run_query(query) %}

{% endmacro %} 