{% macro setup_schema() %}

{% set query %}
    USE ROLE ACCOUNTADMIN;
    USE DATABASE BOOKSHOP;
    CREATE SCHEMA IF NOT EXISTS STAGGING;
    GRANT ALL PRIVILEGES ON SCHEMA STAGGING TO ROLE ACCOUNTADMIN;
    GRANT CREATE TABLE ON SCHEMA STAGGING TO ROLE ACCOUNTADMIN;
    GRANT USAGE ON SCHEMA STAGGING TO ROLE ACCOUNTADMIN;
{% endset %}

{% do run_query(query) %}

{% endmacro %} 